### ISSUE TITLE
profiling the import of pystan results in an error 

### ISSUE THREAD

**Issue by haimivan** [boris-42/profimp#25]
Hi,

I installed `profimp`  via `sudo pip install profimp` on my Ubuntu 14.04 machine.

Afterwards I try to profile the pystan import:
`profimp --html "import pystan"
Traceback (most recent call last):
 File "/usr/local/bin/profimp", line 10, in <module>
   sys.exit(main())
 File "/usr/local/lib/python3.4/dist-packages/profimp/main.py", line 66, in main
   report = reports.to_html(trace_module(sys.argv[arg_pos]))
 File "/usr/local/lib/python3.4/dist-packages/profimp/main.py", line 53, in trace_module
   exec(import_line)
 File "<string>", line 1, in <module>
 File "/usr/local/lib/python3.4/dist-packages/profimp/tracer.py", line 110, in w
   return f(*args, **kwargs)
ImportError: No module named 'pystan'
`

Within python, pystan is available:

`python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.`

`import pystan`
`pystan.__version__`
`'2.18.1.0'
`

What can I do to make this work?

**Comment by boris-42** [comment]
@haimivan I don't have enough details for this, but 2 things: 

- It's usually very bad practice to use "sudo" with "pip" really, you can easily create a mess in your system that is hard to clean (if you install multiple non compatible python packages) I would suggest you to take a look at virtualenv 

- pip - might point to another installed python like python27, and you might not have pystan installed in for python27, I would suggest to take a look whatever you have "pip3" available on your system or install pystan with "pip" as well, either one should solve the problem

**Comment by haimivan** [comment]
Hi @boris-42 ,

thanks for your reply.

regarding the `sudo` installation: I completely agree with you, but I just followed the advice in the README.rst from this project. Perhaps it makes sense to update the README.rst sometimes.

After a `sudo pip uninstall` and a `pip install` now also the `profimp --html "import pystan"` works.

**Comment by boris-42** [comment]
@haimivan oops =) sorry about misleading, updated docs and removed sudo =)

**Comment by haimivan** [comment]
:-) no problem :-)
